### ISSUE TITLE
[SUMO-Integration] Delaunay triangulation doesn't finish

### ISSUE THREAD

**Issue by bcoueraud87** [PedestrianDynamics/jupedsim#1088]
- Current date : 03/04/2023
- Compiler : MSVC
- Commit hash  : c27f9139445aa34d1f55ba0830207819f039cc14
- Commit date : Tue Mar 21 12:02:29 2023 +0100
- Branch : SUMO-Integration

I can't load into JuPedSim the geometry that describes some large pedestrian network, as the Delaunay triangulation that takes place in CGAL doesn't finish.

Some context:
- The polygon comes from GEOS and contains holes. 
- The joint WKT file `pedestrianNetwork_Cpp.txt` loads in `visdbg` but arrays with flattened coordinates  (contained in `pedestrian_network_connected_component_0.txt`) passed to JuPedSim give the problem above.
- The code that produces this flattened arrays of coordinates and the calls to the JuPedSim API are visible [here](https://github.com/eclipse/sumo/blob/jupedsim/src/microsim/transportables/MSPModel_JuPedSim.cpp), function `preparePolygonForJPS`.
- But this code is similar to what `visdbg` does.
- Going into Release mode doesn't solve the issue.
- The infinite triangulation appears after `GeometryBuilder::Build` starts, and then time is lost in various CGAL calls, like  (for example) `CGAL::Surface_sweep`, etc.
- **This code works for networks of smaller size.**

[pedestrian_network_connected_component_0.txt](https://github.com/JuPedSim/jpscore/files/11285338/pedestrian_network_connected_component_0.txt)
[pedestrianNetwork_Cpp.txt](https://github.com/JuPedSim/jpscore/files/11285339/pedestrianNetwork_Cpp.txt)

**Comment by bcoueraud87** [comment]
I uploaded two "corrected" files that wouldn't bring any confusion. The coordinates are now in the same order for both files. Note that the second one is volontarily missing the GEOMETRYCOLLECTION string at its beginning, and that for each polygon in the first one, the last point has been removed to make CGAL happy.

**Comment by Ozaq** [comment]
Underlying issue was the wrong dependency under windows (old version of poly2tri)
