### ISSUE TITLE
late errors for waypoints outside of walkable areas

### ISSUE THREAD

**Issue by behrisch** [PedestrianDynamics/jupedsim#1281]
If I add a waypoint outside of the walkable area, I would expect an error message. But instead I get the error message only when I add an agent using a journey with that waypoint. Unfortunately the agent has probably been added nevertheless (because I get a lot of folllowup errors for the same invalid position then).

**Comment by schroedtert** [comment]
We added tests for all stages, that they need to be inside the walkable area. This is available in the new released version 1.0.4 (already available at pypi)
