### ISSUE TITLE
Feedback to current online documentation

### ISSUE THREAD

**Issue by schroedtert** [PedestrianDynamics/jupedsim#1335]
Feedback from a user, who started using JuPedSim with the help of the website:

- [x] **Exits:** nowhere does it say that they have to be within the walkable area. I would have assumed this in Concepts/geometry, but there is not a word about the exits. Fixed with #1350

- [ ] #1406

- [x] **Getting started:** For distribute agents: It says it goes by number or density, but we don't use that here. In my opinion, there should be a link to the API or to the user guide / concept (if there is a plan to explain this). Otherwise, as a JupedSim newbie, you sit in front of it and get frustrated because you have to search forever for how to distribute people. Because the fact that you already know the positions is a super special case... Fixed with #1350

**Comment by Ozaq** [comment]
>Notebooks: are not consistent in the geometry definition: in some cases there is suddenly something with pedpy and that confuses rather than helps.

@schroedtert what's the proposal to address this? Any idea what consistent should look like? I would like to address this and get the issue closed

**Comment by Ozaq** [comment]
Converted remaining task to own Issue, closing this one.
