### ISSUE TITLE
Documentation for 1.2.0 / 1.2.1 is generated incomplete 

### ISSUE THREAD

**Issue by Ozaq** [PedestrianDynamics/jupedsim#1408]
Documentation for 1.2.0 and 1.2.1 is missing documentation for the available pedestrian models. 

Looks like something in the documentation generation process broke because the docstring is still present but autodoc is not extracting it anymore

**Comment by schroedtert** [comment]
The documentation is still generated but in a subfolder `models`. Not sure why this happens now and before, as we had the same structure already for 1.1 (iirc)

**Comment by Ozaq** [comment]
When we moved the different models into a subfolder, i.e. an implicit package we ran into this bug in autoapi https://github.com/readthedocs/sphinx-autoapi/issues/298.

**Comment by Ozaq** [comment]
Fixed for 1.2.2 / 1.3.0
